export {default as Header} from "./Header.jsx"
export {default as Hero} from "./Hero.jsx"
export {default as About} from "./About.jsx"
export {default as Work} from "./Work.jsx"
export {default as Footer} from "./Footer.jsx"